# Generated by Django 6.0.7 on 2026-07-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
