# Generated by Django 6.0.7 on 2026-07-23 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Retirada na loja'), ('delivery', 'Entrega local')], max_length=20, verbose_name='forma de entrega')),
                ('status', models.CharField(choices=[('received', 'Pedido recebido'), ('preparing', 'Em preparação'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], default='received', max_length=20, verbose_name='status')),
                ('delivery_address', models.CharField(blank=True, max_length=300, verbose_name='endereço de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('coupon_code', models.CharField(blank=True, max_length=40, verbose_name='cupom')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('product_name', models.CharField(max_length=160, verbose_name='produto')),
                ('variation_label', models.CharField(blank=True, max_length=90, verbose_name='variação')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='produto')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariation', verbose_name='variação')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('previous_status', models.CharField(blank=True, choices=[('received', 'Pedido recebido'), ('preparing', 'Em preparação'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], max_length=20, verbose_name='status anterior')),
                ('new_status', models.CharField(choices=[('received', 'Pedido recebido'), ('preparing', 'Em preparação'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], max_length=20, verbose_name='novo status')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'histórico do pedido',
                'verbose_name_plural': 'históricos dos pedidos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['number'], name='orders_orde_number_539d36_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
    ]
