# Generated by Django 6.0.7 on 2026-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='telefone')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='CEP')),
                ('first_order_date', models.DateTimeField(blank=True, null=True, verbose_name='primeiro pedido')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='última compra')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['name'], name='customers_c_name_f018e2_idx')],
            },
        ),
    ]
