# Generated by Django 6.0.7 on 2026-07-23 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('type', models.CharField(choices=[('fixed', 'Valor fixo'), ('percent', 'Percentual')], default='percent', max_length=10, verbose_name='tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(verbose_name='vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='usos máximos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='usos')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx')],
            },
        ),
    ]
